spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF8&connectTimeout=5000&socketTimeout=120000&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always